version: "3.1"

services:
  spock:
    build: .
    tty: true
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_URL: postgresql://db:5432/spock?user=postgres&password=example
    command: stack exec my-first-spock-exe

  db:
    image: postgres
    restart: always
    ports:
      -  5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: spock

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
